### ISSUE TITLE
login

### ISSUE THREAD

**Issue by freddieRv** [freddieRv/code_ediTHOR#1]

**Comment by RodrigoEq** [comment]
![27994810_1619843944720047_1526491552_n](https://user-images.githubusercontent.com/35493402/36170716-c642fd20-10c5-11e8-9582-208d432a3d0e.jpg)

Login

**Comment by freddieRv** [comment]
Creo que el 'forgot my username' esta de mas. Fuera de eso seems pretty good to me.

**Comment by RodrigoEq** [comment]
si se puede hacer login con el correo si esta de más, si es solo con username pues no sé, , igual lo hago sin eso y al final se puede porner fácil

**Comment by freddieRv** [comment]
Pues esta bien que se puedan logear con correo o username, pero si le dan click a "forgot my username" a donde los va a llevar?

**Comment by RodrigoEq** [comment]
una pag que te pida el correo, claro, ya sé es estupido, pero es en caso de que solo se pudiera logear con el username y no con el correo, si es con los dos pues lo quito

**Comment by freddieRv** [comment]
Bueno yo digo que con el "forgot password" es suficiente.
