### ISSUE TITLE
create new project

### ISSUE THREAD

**Issue by freddieRv** [freddieRv/code_ediTHOR#11]

**Comment by freddieRv** [comment]
![create_project](https://user-images.githubusercontent.com/17557452/36556198-f5105714-17c9-11e8-82d4-e1fa47658068.jpg)
@EdgardoDth @RodrigoEq

**Comment by EdgardoDth** [comment]
Me agrada, quiza podriamos ver la opcion de agregar alguna imagen para distigir el proyecto y un usuario administrador @RodrigoEq
