### ISSUE TITLE
project detail (read/show)

### ISSUE THREAD

**Issue by freddieRv** [freddieRv/code_ediTHOR#12]
Must contain a list of all team members and their roles. And maybe some stats and info about the files.

**Comment by freddieRv** [comment]
![team_detail_view](https://user-images.githubusercontent.com/17557452/36440091-7ab1e82a-1634-11e8-8bbf-a62f0d9f6cae.jpg)
@EdgardoDth @RodrigoEq

**Comment by freddieRv** [comment]
![team_detail_2](https://user-images.githubusercontent.com/17557452/36440563-725fa85a-1635-11e8-9ec8-6ecefe02f879.jpg)

**Comment by EdgardoDth** [comment]
@freddieRv actuliza conforme se acordo,"proyectos"

**Comment by freddieRv** [comment]
![project_detail](https://user-images.githubusercontent.com/17557452/36555828-bd4fa7d6-17c8-11e8-9caf-d33022c0565e.jpg)
